#!/usr/bin/env php
<?php
include './src/cmdautold.php';
#Execute only from Command-line-interface
if (php_sapi_name() !== 'cli') {
    HlprCls::errorInCmd("This script can only be run from the command line.");
}
HndlCmd::excCmd($argv);