#!/usr/bin/env php
<?php

# Including auto load function for classess
$crwrkdir = getcwd();
include $crwrkdir.'vendor/deepaktiwari/php-cmds/src/cmdautold.php';

#Execute only from Command-line-interface
if (php_sapi_name() !== 'cli') {
    HlprCls::errorInCmd("This script can only be run from the command line.");
}
HndlCmd::excCmd($argv);