#!/usr/bin/env php
<?php

#Include class
include 'cmdautold.php';
try {
    $fileCrt = getcwd()."/".($argv[1] ?? 'framework');
    HlprCls::createFile($fileCrt, "#!/usr/bin/env php\n<?php\ninclude 'vendor/deepaktiwari/php-cmds/src/cmdautold.php';\n#Execute only from Command-line-interface\nif (php_sapi_name() !== 'cli') {\n    HlprCls::errorInCmd('This script can only be run from the command line.');\n}\nHndlCmd::excCmd(\$argv);");
} catch (\Throwable $th) {
    HlprCls::errorInCmd("Unable to genrate your cmd!");
}
